name = "AdriaArrayPicker"
uuid = "10cbbe04-4d51-483e-8de5-7c05df3150f1"
authors = ["Marcel Thielmann"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
